version: '2'

services:
  mysql:
    image: mysql:5.7
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    container_name: mysql-dev
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./.data/db:/var/lib/mysql
